### ISSUE TITLE
Feature: Working example for Owee_location

### ISSUE THREAD

**Issue by lukepalmer** [def-lkb/owee#13]
Thanks for doing this, it seems very handy!

I'm not able to get exposed functions in Owee_location to do... anything. I'm sure I'm doing something simple incorrectly. 

Would it be possible to add a usage of Owee_location to examples?

This would both help as a starting point for usage and, if there is indeed something wrong, would help me begin debugging.

**Comment by let-def** [comment]
A small example:

__locate.ml__
```ocaml
let f () = ()                                                                   
                                                                                
let () =                                                                        
  match Owee_location.locate f with                                             
  | None -> print_endline "No location for f"                                   
  | Some (filename, line, column) ->                                            
    Printf.printf "f is defined in %s, line %d, column %d\n" filename line column
```
```shell
$ dune exec ./locate.exe
f is defined in locate.ml, line 1, column 6
```

There are a few restrictions though... First, it works only on Linux amd64.
Then, I discovered that recent GCCs produce dwarf version 5, which is not supported by this library, only versions 2 to 4 are handled.
If you happen to be in this situation, a workaround is to pass `-gdwarf-4` to `gcc` and `as` commands. I did that by wrapping the commands with a shell script that pass that extra argument.

**Comment by let-def** [comment]
Closing. This should now be addressed by the partial DWARF 5 support.
