### ISSUE TITLE
nice library, what about a release?

### ISSUE THREAD

**Issue by hannesm** [def-lkb/owee#17]
Hey Fred,

what a great library. Would you mind to cut a release? the most recent one (0.3) in opam-repository does not include support for OCaml 4.12+.

Thanks,

Hannes

**Comment by let-def** [comment]
Hmm, I can surely release a new package.

I have been stuck with the lack of support for Dwarf 5, which makes owee useless for anyone with a recent version of GCC (at least all Arch users).

**Comment by hannesm** [comment]
From my point of view, owee is pretty useful -- at least with cland (10.x and / 11.y -- both emit dwarf 4) on my FreeBSD system. The last released version is - as mentioned - slightly incompatible with current OCaml compiler, thus I need to pin owee to `--dev`, which makes it a bit unpleasent. Of course, supporting dwarf 5 would be great as well, but that may not happen overnight. So, TL;DR: a release of the master branch now would be nice. :)

**Comment by let-def** [comment]
Indeed, that is unpleasant. I will do a release now. Sorry for the delay.

**Comment by hannesm** [comment]
thanks a lot

**Comment by constfun** [comment]
Thank you for the release
