### ISSUE TITLE
examples/decodedline_macho.ml broken in 0.5

### ISSUE THREAD

**Issue by reynir** [def-lkb/owee#21]
`Owee_debug_line.read_chunk` now takes an additional `~pointers_to_other_sections` argument.
https://github.com/let-def/owee/blob/e5616888c32dbdaafd9f05224a533d66d0811b52/examples/decodedline_macho.ml#L29

**Comment by reynir** [comment]
Ah, I see it's a known problem from the Makefile...

**Comment by let-def** [comment]
Yes, I don't use macOS, so I couldn't properly work the Mach-O support. Sorry for that.
Patches are welcome :bow: .
