### ISSUE TITLE
Owee spends a lot of time sorting intervals

### ISSUE THREAD

**Issue by Xyene** [def-lkb/owee#23]
Hi!

While working on magic-trace, we found that we spend a long time (~20-30 seconds) loading some decently-sized binaries with Owee. These binaries have ~2 million symbols.

I captured a ~1ms trace of this:

![p](https://user-images.githubusercontent.com/1403503/163248501-a9c96c91-a9f5-46e5-b1d1-bda25ddca913.png)

It's all in building `Owee_interval_tree`s.

I think we can build it substantially quicker while maintaining query speed, since we have the advantage of knowing up front all the symbols (such that we never have online interval additions), and we have functional maps. (Thanks @FatalEagle for much help with the algorithm here.) We would be building a sort of "prefix sum of maps".

Below is some simple pseudocode for replacing `Owee_interval_tree`, while allowing it to be built much faster:

```ocaml
type t = {
   maps : Map[left bound int, Map[right bound int, symbol]]
   ; cumulative_right_bound_to_interval_map : Map[right bound int, symbol]
}

fun build intervals:
    maps = {}
    cumulative_right_bound_to_interval_map = {}

    for ({ symbol = _, left, right } as interval) in intervals sorted by nondecreasing left bound:
        (* This step is "free" thanks to functional maps *)
        cumulative_right_bound_to_interval_map |= { right: interval }
        maps[left_bound] = cumulative_right_bound_to_interval_map

    return { maps; cumulative_right_bound_to_interval_map }

fun iter f:
    map(f, cumulative_right_bound_to_interval_map.values())

fun query addr:
    (* O(log n) time, n = size of [maps]
     * This is implementable with closest_key `Less_or_equal_to
     * https://ocaml.janestreet.com/ocaml-core/v0.12/doc/base/Base/Map/index.html#val-closest_key *)
    right_map = binary search maps for greatest left bound <= addr
	
    (* O(log n) time, n = size of [right_map]
     * This is implementable with [to_sequence ~lower_bound:<bound from above> ~upper_bound:addr]
     * https://ocaml.janestreet.com/ocaml-core/v0.12/doc/base/Base/Map/index.html#val-to_sequence *)
    return (right_map filtered for right bound >= addr).values()
```

The catch here is that while `query` is conceptually simple, `closest_key` and `to_sequence` are not provided in the standard library. Are we willing to take a dependency on `Base` here?

**Comment by let-def** [comment]
Thanks for reporting the issue and suggesting an algorithm, I will implement it. I would try to avoid depending on base though.

**Comment by Xyene** [comment]
Closing since this has been resolved. Thanks a lot for the quick resolution and release!
